name: OddLight
main: info.somethingodd.OddLight.OddLight
version: 0.6
website: http://bukkit.somethingodd.info
author: petteyg359
description: >
             Torch expiration.
commands:
  oddlight:
    usage: |
           /<command> duration [duration]
              - Print or set duration
           /<command> worlds [world1 world2 ... world#]
              - Print or set worlds
           /<command> add|del <world>
load: STARTUP